[package]
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
description = "Micro multiplexer"
license = "MIT"
name = "umux"
version = "1.0.0"

[[bin]]
name = "umux"

[dependencies]
clippy = "0.0.95"
error-chain = "0.5.0"
ncurses = "5.83.0"
nix = "0.7.0"
regex = "0.1.77"
